# Generated by Django 3.1.5 on 2021-02-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=300)),
                ('blog_data', models.DateTimeField()),
                ('blog_text', models.CharField(max_length=300)),
                ('blog_image', models.ImageField(upload_to='event_images/')),
            ],
        ),
    ]
